### ISSUE TITLE
legacy mode when calculating cell centres

### ISSUE THREAD

**Issue by CBermingham** [CBermingham/bacteria_analysis_scripts#11] opened 2018-11-05 16:56 UTC
In legacy mode 0 or 1 a csv file of cell centres in expected, but this is not always there as the cell centres can be calculated from the python code.

**Comment by payoto** [comment] 2018-11-07 09:31
Hi Charlotte,

Could you add the reason this was not working and what you did to fix it?
It might be useful to other people who might get the same issue?

Thanks a lot,

Alex

**Comment by CBermingham** [comment] 2018-11-07 09:32
Create csv file for cell centres before running

**Comment by payoto** [comment] 2018-11-07 10:53
I'm going to reopen this issue as this is not the intended behaviour. It should run without a `"_sample"` CSV file, if recalculations of cell centres is turned on (`recalc_centre=True`).

**Comment by payoto** [comment] 2018-11-07 18:21
Fixed in pull-request #10

**Closed by payoto** 2018-11-07 18:21 UTC
